config/routes.rb
Rails.application.routes.draw do
  
  resources :price_tables
  resources :product_categories
  resources :sales_agents
  resources :sales
  resources :products
  root 'home#index'

end

app/controllers/price_tables_controller.rb
class PriceTablesController < ApplicationController
  before_action :set_price_table, only: [:show, :edit, :update, :destroy]

  # GET /price_tables
  # GET /price_tables.json
  def index
    @price_tables = PriceTable.all
  end

  # GET /price_tables/1
  # GET /price_tables/1.json
  def show
  end

  # GET /price_tables/new
  def new
    @price_table = PriceTable.new
  end

  # GET /price_tables/1/edit
  def edit
  end

  # POST /price_tables
  # POST /price_tables.json
  def create
    @price_table = PriceTable.new(price_table_params)

    respond_to do |format|
      if @price_table.save
        format.html { redirect_to @price_table, notice: 'Price table was successfully created.' }
        format.json { render :show, status: :created, location: @price_table }
      else
        format.html { render :new }
        format.json { render json: @price_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_tables/1
  # PATCH/PUT /price_tables/1.json
  def update
    respond_to do |format|
      if @price_table.update(price_table_params)
        format.html { redirect_to @price_table, notice: 'Price table was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_table }
      else
        format.html { render :edit }
        format.json { render json: @price_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_tables/1
  # DELETE /price_tables/1.json
  def destroy
    @price_table.destroy
    respond_to do |format|
      format.html { redirect_to price_tables_url, notice: 'Price table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_table
      @price_table = PriceTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_table_params
      params.require(:price_table).permit(:price, :active_status, :del_status, :user_id)
    end
end

app/helpers/price_tables_helper.rb
module PriceTablesHelper
end

app/views/price_tables/_form.html.erb
<%= simple_form_for(@price_table) do |f| %>


  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin">
    <%= f.input :price ,input_html:{class: 'form-control'} %>
    <%= f.input :active_status,as: :hidden, input_html:{value: 1,class: 'form-control w3-input'} %>
    <%= f.input :del_status,as: :hidden, input_html:{value: 0,class: 'form-control w3-input'}  %>
    <%= f.input :user_id,as: :hidden %>
  </div>

  <div class="w3-container">

    <%= link_to 'Back', price_tables_path,class: 'w3-btn w3-white w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' %>
    <%= f.button :submit,class: 'w3-btn w3-white w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-right' %>
  </div>
<% end %>

app/views/price_tables/edit.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4">
    <h1 class="w3-center">Editing Price Table</h1>
    <%= render 'form' %>
</div>
<div class="col-md-4"></div>

app/views/price_tables/index.html.erb
<div class="col-md-1"></div>
<div class="w3-container col-md-10 w3-responsive">
<h1 class="w3-center">Price Tables</h1>

<table class="w3-container w3-table-all table-striped">
  <thead>
    <tr class="w3-blue">
      <th>Price</th>
      <!--<th>Active status</th>-->
      <!--<th>Del status</th>-->
      <th>User</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_tables.each do |price_table| %>
      <tr>
        <td><%= price_table.price %></td>
        <td><%#= price_table.active_status,as: :hidden %></td>
        <td><%#= price_table.del_status %></td>
        <td><%= price_table.user_id %></td>
        <td><%= link_to 'Show', price_table,class: 'w3-btn w3-border w3-border-blue w3-round w3-small w3-hover-blue w3-hover-text-white' %></td>
        <td><%= link_to 'Edit', edit_price_table_path(price_table),class: 'w3-btn w3-border w3-border-green w3-round w3-small w3-hover-green w3-hover-text-white' %></td>
        <td><%= link_to 'Destroy', price_table, method: :delete, data: { confirm: 'Are you sure?' },class: 'w3-btn w3-border w3-border-red w3-round w3-small w3-hover-red w3-hover-text-white' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

    <%= link_to 'New Price table', new_price_table_path,class: 'w3-button w3-white w3-border w3-border-green w3-round-large w3-hover-green w3-hover-text-white w3-left' %>
</div>
  <div class="col-md-1"></div>

app/views/price_tables/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 w3-container">
    <h1 class="w3-center">New Price Table</h1>
    <%= render 'form' %>
</div>
<div class="sol-md-4"></div>

app/views/price_tables/show.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4">

  <div class="w3-container w3-card-4 w3-center w3-light-grey w3-text-blue w3-margin" style="padding-bottom: 6%; padding-top:2%;">
    <p id="notice"><%= notice %></p>
    <table class="w3-table w3-border table-bordered">
      <tr>
        <td class="w3-blue"><strong>Price </strong></td><td style="padding-left: 6%"><%= @price_table.price %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>User </strong></td><td style="padding-left: 6%"><%= @price_table.user_id %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Active Status </strong></td><td style="padding-left: 6%"><%= @price_table.active_status %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Del Status </strong></td><td style="padding-left: 6%"><%= @price_table.del_status %></td>
      </tr>

    </table>
  </div>


    <div class="w3-container">
    <%= link_to 'Back', price_tables_path,class: 'w3-btn w3-white w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' ,style:'margin-right: 4px' %>
    <%= link_to 'Edit', edit_price_table_path(@price_table),class: 'w3-btn w3-white w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-left' %>
    </div>
</div>
<div class="col-md-4"></div>