config/routes.rb
Rails.application.routes.draw do
  
  resources :price_tables
  resources :product_categories
  resources :sales_agents
  resources :sales
  resources :products
  root 'home#index'

end

app/models/sales_agent.rb
class SalesAgent < ActiveRecord::Base
  belongs_to :sale ,class_name: 'Sale', foreign_key: :agent_id
end

app/controllers/sales_agents_controller.rb
class SalesAgentsController < ApplicationController
  before_action :set_sales_agent, only: [:show, :edit, :update, :destroy]

  # GET /sales_agents
  # GET /sales_agents.json
  def index
    @sales_agents = SalesAgent.all
  end

  # GET /sales_agents/1
  # GET /sales_agents/1.json
  def show
  end

  # GET /sales_agents/new
  def new
    @sales_agent = SalesAgent.new
  end

  # GET /sales_agents/1/edit
  def edit
  end

  # POST /sales_agents
  # POST /sales_agents.json
  def create
    @sales_agent = SalesAgent.new(sales_agent_params)

    respond_to do |format|
      if @sales_agent.save
        format.html { redirect_to @sales_agent, notice: 'Sales agent was successfully created.' }
        format.json { render :show, status: :created, location: @sales_agent }
      else
        format.html { render :new }
        format.json { render json: @sales_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_agents/1
  # PATCH/PUT /sales_agents/1.json
  def update
    respond_to do |format|
      if @sales_agent.update(sales_agent_params)
        format.html { redirect_to @sales_agent, notice: 'Sales agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_agent }
      else
        format.html { render :edit }
        format.json { render json: @sales_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_agents/1
  # DELETE /sales_agents/1.json
  def destroy
    @sales_agent.destroy
    respond_to do |format|
      format.html { redirect_to sales_agents_url, notice: 'Sales agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_agent
      @sales_agent = SalesAgent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_agent_params
      params.require(:sales_agent).permit(:surname, :other_names, :dob, :gender, :tel_number, :location_address, :age, :active_status, :del_status, :user_id)
    end
end

app/helpers/sales_agents_helper.rb
module SalesAgentsHelper
end

app/views/sales_agents/_form.html.erb
<%= simple_form_for(@sales_agent) do |f| %>
  <%= f.error_notification %>

  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin">
    <br/>
    <%= f.input :surname %>
    <%= f.input :other_names %>
    <%= f.input :dob %>
    <%= f.input :gender %>
    <%= f.input :tel_number %>
    <%= f.input :location_address %>
    <%= f.input :age %>
    <%= f.input :active_status, as: :hidden, input_html: {value: 1, class: 'form-control w3-input'}  %>
    <%= f.input :del_status, as: :hidden, input_html: {value: 0, class: 'form-control w3-input'}  %>
    <%= f.input :user_id, as: :hidden %>
    <br/>
  </div>

  <div class="w3-container">
    <%= f.button :submit,class:'w3-btn w3-white w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-right' %>
    <%= link_to 'Back', sales_agents_path,class:'w3-btn w3-white w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' %>
  </div>
    <br/>
<% end %>

app/views/sales_agents/edit.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4">
<h1 class="w3-center">Editing Sales Agent</h1>

    <%= render 'form' %>
</div>
<div class="col-md-4"></div>

app/views/sales_agents/index.html.erb
<div class="col-md-1"></div>
<div class="w3-container col-md-10 w3-responsive">
<p id="notice"><%= notice %></p>

<h1>Sales Agents</h1>

<table class="w3-container w3-table-all table-striped">
  <thead>
    <tr class="w3-blue">
      <th>Surname</th>
      <th>Other names</th>
      <th>Dob</th>
      <th>Gender</th>
      <th>Tel number</th>
      <th>Location address</th>
      <th>Age</th>
      <!--<th>Active status</th>-->
      <!--<th>Del status</th>-->
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_agents.each do |sales_agent| %>
      <tr>
        <td><%= sales_agent.surname %></td>
        <td><%= sales_agent.other_names %></td>
        <td><%= sales_agent.dob %></td>
        <td><%= sales_agent.gender %></td>
        <td><%= sales_agent.tel_number %></td>
        <td><%= sales_agent.location_address %></td>
        <td><%= sales_agent.age %></td>
        <!--<td><%#= sales_agent.active_status %></td>-->
        <!--<td><%#= sales_agent.del_status %></td>-->
        <td><%= sales_agent.user_id %></td>
        <td><%= link_to 'Show', sales_agent,class: 'w3-btn w3-border w3-border-blue w3-round w3-small w3-hover-blue w3-hover-text-white' %></td>
        <td><%= link_to 'Edit', edit_sales_agent_path(sales_agent),class: 'w3-btn w3-border w3-border-green w3-round w3-small w3-hover-green w3-hover-text-white' %></td>
        <td><%= link_to 'Destroy', sales_agent, method: :delete, data: { confirm: 'Are you sure?' },class: 'w3-btn w3-border w3-border-red w3-round w3-small w3-hover-red w3-hover-text-white' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sales agent', new_sales_agent_path,class: 'w3-button w3-white w3-border w3-border-green w3-round-large w3-hover-green w3-hover-text-white w3-left' %>
</div>
<div class="col-md-1"></div>

app/views/sales_agents/new.html.erb
<div class="col-md-4"></div>
<div class="w3-container col-md-4">
    <h1 class="w3-center">New Sales Agent</h1>
    <%= render 'form' %>
</div>
<div class="col-md-4"></div>

app/views/sales_agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @sales_agent.surname %>
</p>

<p>
  <strong>Other names:</strong>
  <%= @sales_agent.other_names %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @sales_agent.dob %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @sales_agent.gender %>
</p>

<p>
  <strong>Tel number:</strong>
  <%= @sales_agent.tel_number %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @sales_agent.location_address %>
</p>

<p>
  <strong>Age:</strong>
  <%= @sales_agent.age %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @sales_agent.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @sales_agent.del_status %>
</p>

<p>
  <strong>User:</strong>
  <%= @sales_agent.user_id %>
</p>
<div class="w3-container col-md-4">
  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin" style="padding-bottom: 6%; padding-top:2%;">
    <p id="notice"><%= notice %></p>
    <table class="w3-table w3-border table-bordered">
      <tr>
        <td class="w3-blue"><strong>Surname </strong></td><td style="padding-left: 6%"><%= @sales_agent.surname %></td>
      </tr>
      <tr>
        <td class="w3-blue"><strong>Other names </strong></td><td style="padding-left: 6%"><%= @sales_agent.other_names %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Dob </strong></td><td style="padding-left: 6%"><%= @sales_agent.dob %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Gender </strong></td><td style="padding-left: 6%"><%= @sales_agent.gender %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Tel number </strong></td><td style="padding-left: 6%"><%= @sales_agent.tel_number %></td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Location address </strong></td><td style="padding-left: 6%"><%= @sales_agent.location_address %></td>
      </tr>

    </table>
  </div>
  <div class="w3-container">
    <%= link_to 'Back', sales_agents_path,class: 'w3-btn w3-white w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' ,style:'margin-right: 4px' %>
    <%= link_to 'Edit', edit_sales_agent_path(@sales_agent),class: 'w3-btn w3-white w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-left' %>
  </div>
</div>
<div class="col-md-4"></div>