config/routes.rb
Rails.application.routes.draw do
  
  resources :price_tables
  resources :product_categories
  resources :sales_agents
  resources :sales
  resources :products
  root 'home#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :sales_agents
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @users_sale=SalesAgent.all
  end

  # GET /sales/1/edit
  def edit
    @users_sale=SalesAgent.all
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:product_id, :quantity, :agent_id, :date_time, :user_id, :active_status, :del_status)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>

  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin">
    <%= f.input :product_id %>
    <%= f.input :quantity %>
    <%= f.input :agent_id %>
    <%= f.input :date_time %>
    <%= f.input :user_id ,as: :hidden,input_html: {value: @users_sale, class: 'form-control w3-input'}%>
    <%= f.input :active_status,as: :hidden ,input_html: {value: 1, class: 'form-control w3-input'}%>
    <%= f.input :del_status,as: :hidden,input_html: {value: 0, class: 'form-control w3-input'} %>
  </div>

  <div class="w3-container">
    <%= f.button :submit,class: 'w3-btn w3-white w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-right' %>
    <%= link_to 'Back',sales_path,class: 'w3-btn w3-white w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Agent</th>
      <th>Date time</th>
      <th>User</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.product_id %></td>
        <td><%= sale.quantity %></td>
        <td><%= sale.agent_id %></td>
        <td><%= sale.date_time %></td>
        <td><%= sale.user_id %></td>
        <td><%= sale.active_status %></td>
        <td><%= sale.del_status %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
  <h1 class="w3-center">New Sale</h1>
  <%= render 'form' %>
</div>
<div class="col-md-4"></div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-4"></div>
<div class="w3-container col-md-4">
  <div class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin" style="padding-bottom: 6%; padding-top:2%;">
    <p id="notice"><%= notice %></p>
    <table class="w3-table w3-border table-bordered">
      <tr>
        <td class="w3-blue"><strong>Product </strong></td><td style="padding-left: 6%">
          <%= @sale.product_id %>
      </tr>
      <tr>
        <td class="w3-blue"><strong>Quantity </strong></td><td style="padding-left: 6%">
          <%= @sale.quantity %>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Agent </strong></td><td style="padding-left: 6%">
          <%= @sale.agent_id %>
        </td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Date time </strong></td><td style="padding-left: 6%">
          <%= @sale.date_time %>
        </td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>User </strong></td><td style="padding-left: 6%">
          <%= @sale.user_id %>
        </td>
      </tr>

      <tr>
        <td class="w3-blue"><strong>Active status </strong></td><td style="padding-left: 6%">
          <%= @sale.active_status %>
        </td>
      </tr>


      <tr>
        <td class="w3-blue"><strong>Del status </strong></td><td style="padding-left: 6%">
        <%= @sale.del_status %>
      </td>
      </tr>

    </table>
  </div>
  <div class="w3-container">
    <%= link_to 'Back', sales_path,class: 'w3-btn w3-white w3-border w3-border-black w3-round-large w3-hover-black w3-hover-text-white w3-left' ,style:'margin-right: 4px'%>
    <%= link_to 'Edit', edit_sale_path(@sale),class: 'w3-btn w3-white w3-border w3-border-blue w3-round-large w3-hover-blue w3-hover-text-white w3-left' %>

  </div>
</div>
<div class="col-md-4"></div>