config/routes.rb
Rails.application.routes.draw do
  
  resources :price_tables
  resources :product_categories
  resources :sales_agents
  resources :sales
  resources :products
  root 'home#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="container w3-lobster w3-large" id="switching" style="width: 400px; height: 25px;">
  <div class="row">
    <div id="alert_message" class=" w3-card-4 alert alert-<%= name.to_s == 'notice' ? 'info' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>

      <%#= flash[:alert] %>
      <%#= flash[:notice] = "The message was sent..." %>

    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default w3-blue">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
          <%= image_tag ('fan-milk.jpg'), class: "w3-left w3-margin-right w3-margin-left", style: "margin-top: 5px; width:50px; padding-bottom: 5px;" %>
          <b class="navbar-brand " style="color:#fff; ">Inventory Management System</b>
      <% end %>

        </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to 'Home', root_path %></li>
        <li><%= render 'layouts/navigation_links' %></li>
        
      </ul>
      
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li class=" w3-hover-blue-grey">
	<%= link_to 'Sales', sales_path %>
</li >

<li class=" w3-hover-blue-grey">
	<%= link_to 'Product', products_path %>
</li>

<li class=" w3-hover-blue-grey">
	<%= link_to 'Product Category', product_categories_path %>
</li>

<li class=" w3-hover-blue-grey" >
	<%= link_to 'Prices', price_tables_path %>
</li>


<li class=" w3-hover-blue-grey">
	<%= link_to 'Sales Agents', sales_agents_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fan Milk" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fan Milk" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>


  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>